name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install libgtest-dev libfmt-dev && cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp lib/*.a /usr/lib

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -B build -S ..
      working-directory: build

    - name: Build
      run: cmake --build .
      working-directory: build

    - name: Run Tests
      run: ./AlgorithmTests
      working-directory: build
